/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--color-background)",
        "bg-subtle": "var(--color-background-subtle)",
        surface: "var(--color-surface)",
        "surface-hover": "var(--color-surface-hover)",
        "surface-secondary": "var(--color-surface-secondary)",
        "surface-tertiary": "var(--color-surface-tertiary)",
        "surface-raised": "var(--color-surface-raised)",
        elevated: "var(--color-surface-elevated)",
        card: "var(--color-card)",
        border: "var(--color-border)",
        "border-subtle": "var(--color-border-subtle)",
        "border-strong": "var(--color-border-strong)",
        brand: "var(--color-brand)",
        "brand-hover": "var(--color-brand-hover)",
        "brand-active": "var(--color-brand-active)",
        "brand-soft": "var(--color-brand-soft)",
        "brand-muted": "var(--color-brand-muted)",
        "on-brand": "var(--color-on-brand)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-active": "var(--color-accent-active)",
        "accent-soft": "var(--color-accent-soft)",
        "on-accent": "var(--color-on-accent)",
        "text-primary": "var(--color-text)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-disabled": "var(--color-text-disabled)",
        success: "var(--color-success)",
        complete: "var(--color-complete)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
        ash: {
          0: "var(--ash-0)",
          50: "var(--ash-50)",
          100: "var(--ash-100)",
          200: "var(--ash-200)",
          300: "var(--ash-300)",
          400: "var(--ash-400)",
          500: "var(--ash-500)",
          600: "var(--ash-600)",
          700: "var(--ash-700)",
          800: "var(--ash-800)",
          900: "var(--ash-900)",
          950: "var(--ash-950)",
        },
        violet: {
          300: "var(--violet-300)",
          400: "var(--violet-400)",
          500: "var(--violet-500)",
          600: "var(--violet-600)",
          700: "var(--violet-700)",
          800: "var(--violet-800)",
        },
        orange: {
          300: "var(--orange-300)",
          400: "var(--orange-400)",
          500: "var(--orange-500)",
          600: "var(--orange-600)",
          700: "var(--orange-700)",
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Space Grotesk', 'Inter', 'ui-sans-serif', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderRadius: {
        xs: "6px",
        sm: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        btn: "8px",
        card: "12px",
        panel: "16px",
        feature: "16px",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        brand: "var(--shadow-brand)",
      },
      maxWidth: { container: "var(--container-width)" },
    },
  },
  plugins: [],
};
